# Generated by Django 4.1.2 on 2022-10-12 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('disable_contact', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(upload_to='content_image/')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='TypeAura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descriptions', models.TextField()),
            ],
            options={
                'verbose_name': 'Type Aura',
                'verbose_name_plural': 'Types Aura',
            },
        ),
        migrations.CreateModel(
            name='TypeSeizure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descriptions', models.TextField()),
            ],
            options={
                'verbose_name': 'Type Seizure',
                'verbose_name_plural': 'Types Seizure',
            },
        ),
        migrations.CreateModel(
            name='Aura',
            fields=[
                ('when', models.TimeField(default=datetime.date.today)),
                ('duration', models.DurationField()),
                ('trigger', models.CharField(max_length=150)),
                ('descriptions_trigger', models.TextField()),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.typeaura')),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Aura',
                'verbose_name_plural': 'Aura',
            },
        ),
        migrations.CreateModel(
            name='Seizure',
            fields=[
                ('when', models.TimeField(default=datetime.date.today)),
                ('duration', models.DurationField()),
                ('trigger', models.CharField(max_length=150)),
                ('descriptions_trigger', models.TextField()),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.typeseizure')),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Seizure',
                'verbose_name_plural': 'Seizure',
            },
        ),
    ]
